name:          Riftside Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML, CSS and PHP.
url:           https://riftside.net

markdown:      rdiscount
permalink:     pretty
pygments:      true
